### ISSUE TITLE
Knife supermaket install stops on deprecated zlib

### ISSUE THREAD

**Issue by WebSpider** [atomic-penguin/cookbook-gitlab-deprecated#126]
When installing the gitlab cookbook using 'knife supermarket install gitlab', the install crashes due to an error in a deprecated cookbook, zlib:

```
user@host:~/chef/repo/cookbooks$ knife supermarket install gitlab
Installing gitlab to /home/user/chef/repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-gitlab) exists, switching to it.
Downloading gitlab from Supermarket at version 7.7.1 to /home/user/chef/repo/cookbooks/gitlab.tar.gz
Cookbook saved:
...
Checking out the master branch.
Installing zlib to /home/user/chef/repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-zlib) exists, switching to it.
ERROR: TypeError: no implicit conversion of nil into String

```

**Comment by atomic-penguin** [comment]
I turned over the supermarket namespace for Gitlab to a Chef, Inc. liaison who was going to transfer control of that namespace to Gitlab the company, at their request.  I don't know what happened with that, but I have stopped updating that artifact, and I no longer maintain this piece of code.
